version: '3.8'

services:
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'tienda-network'

  products-service:
    build: products-service
    mem_limit: 512m
    ports:
      - "8082:8082"
      - "8083:8083"
    networks:
      - 'tienda-network'

  carts-service:
    build: carts-service
    mem_limit: 512m
    ports:
      - "8084:8084"
      - "8085:8085"
    networks:
      - 'tienda-network'

  sales-service:
    build: sales-service
    mem_limit: 512m
    ports:
      - "8086:8086"
      - "8087:8087"
    networks:
      - 'tienda-network'

  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'tienda-network'

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=products-service
      - MYSQL_DATABASE=carts-service
      - MYSQL_DATABASE=sales_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - 'tienda-network'

volumes:
  mysql_data:

networks:
  tienda-network:
