spring:
  application:
    name: sales-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://mysqldb:3306/sales_service?serverTimezone=UTC
    username: root
    password: mysql
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-sv:8761/eureka
